#!/usr/bin/env bun
// Merge the tier-1 typo sources into one map the fcitx5 module loads.
//
//   bun tools/build-typomap.ts            -> build/typomap.tsv + a report on stderr
//
// The rule that matters: never auto-change a word Fred could have meant. So a
// pair is DROPPED when:
//   - the typo is a real word (data/dict/en_US.txt + /usr/share/dict SCOWL lists)
//   - the typo is shorter than 3 letters
//   - the source lists more than one fix (Wikipedia "a->b, c")
//   - two sources disagree on the fix
//   - the typo and the fix are the same word
//   - the fix isn't a real word itself (junk generated entries)
//   - it only comes from typofixer and is under 4 letters (too ambiguous)
// The output is generated, not committed: it mixes CC BY-SA, GPL-3.0 and MIT
// sources, each of which keeps its own licence file under data/sources/.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dir, "..");
const src = (p: string) => join(root, "data", p);

type Pair = { typo: string; fix: string; source: string };

// The committed dictionary plus the system SCOWL lists (pacman `words`) when
// present. They're only used here to reject typos that are real words, so
// they're never redistributed. British is included so "colour" is never "fixed".
const dictFiles = [
  src("dict/en_US.txt"),
  "/usr/share/dict/american-english",
  "/usr/share/dict/british-english",
];
const dict = new Set<string>();
for (const f of dictFiles) {
  let text: string;
  try { text = readFileSync(f, "utf8"); } catch { console.error(`  (no ${f}, skipped)`); continue; }
  for (const w of text.split("\n")) {
    const word = w.trim().toLowerCase().replace(/'s$/, "");
    if (word) dict.add(word);
  }
}

function wikipedia(): Pair[] {
  return readFileSync(src("sources/wikipedia_for_machines.txt"), "utf8")
    .split("\n")
    .filter((l) => l && !l.startsWith("#") && l.includes("->"))
    .map((l) => {
      const [typo, fix] = l.split("->");
      return { typo: typo.trim(), fix: fix.trim(), source: "wikipedia" };
    });
}

function typofixer(): Pair[] {
  const data: Record<string, string[]> = JSON.parse(
    readFileSync(src("sources/typofixer/en.json"), "utf8"),
  );
  return Object.entries(data).flatMap(([fix, typos]) =>
    typos.map((typo) => ({ typo, fix, source: "typofixer" })),
  );
}

function smartcomplete(): Pair[] {
  return readFileSync(src("sources/smartcomplete_en_typo_map.txt"), "utf8")
    .split("\n")
    .filter((l) => l && !l.startsWith("#"))
    .map((l) => {
      const [typo, fix] = l.split("\t");
      return { typo: typo?.trim() ?? "", fix: fix?.trim() ?? "", source: "smartcomplete" };
    });
}

const dropped: Record<string, number> = {};
const drop = (why: string) => (dropped[why] = (dropped[why] ?? 0) + 1);

const merged = new Map<string, { fix: string; sources: Set<string> }>();
const conflicted = new Set<string>();

for (const p of [...wikipedia(), ...typofixer(), ...smartcomplete()]) {
  const typo = p.typo.toLowerCase();
  const fix = p.fix;
  if (!typo || !fix) { drop("empty"); continue; }
  if (fix.includes(",")) { drop("ambiguous fix"); continue; }
  if (!/^[a-z']+$/.test(typo)) { drop("typo not a plain word"); continue; }
  if (typo.length < 3) { drop("typo under 3 letters"); continue; }
  if (typo === fix.toLowerCase()) { drop("typo equals fix"); continue; }
  if (dict.has(typo)) { drop("typo is a real word"); continue; }
  // typofixer is generated and noisy ("allignmenterror", "thn" -> then or than?),
  // so its fixes must be real words and its typos a little longer.
  if (!fix.toLowerCase().split(/[ ]+/).every((w) => dict.has(w.replace(/'s$/, "")) || /'/.test(w))) {
    drop("fix is not a real word"); continue;
  }
  if (p.source === "typofixer" && typo.length < 4) { drop("typofixer typo under 4 letters"); continue; }

  const seen = merged.get(typo);
  if (!seen) {
    merged.set(typo, { fix, sources: new Set([p.source]) });
  } else if (seen.fix.toLowerCase() === fix.toLowerCase()) {
    seen.sources.add(p.source);
  } else {
    conflicted.add(typo);
  }
}
for (const typo of conflicted) merged.delete(typo);

const rows = [...merged.entries()].sort(([a], [b]) => a.localeCompare(b));
mkdirSync(join(root, "build"), { recursive: true });
writeFileSync(
  join(root, "build", "typomap.tsv"),
  "# generated by tools/build-typomap.ts; do not edit. typo<TAB>fix\n" +
    rows.map(([typo, { fix }]) => `${typo}\t${fix}`).join("\n") + "\n",
);

const bySource: Record<string, number> = {};
for (const [, { sources }] of rows)
  for (const s of sources) bySource[s] = (bySource[s] ?? 0) + 1;

console.error(`typomap: ${rows.length} pairs -> build/typomap.tsv`);
console.error(`  kept per source (overlaps counted in each): ${JSON.stringify(bySource)}`);
console.error(`  dropped: ${JSON.stringify({ ...dropped, "sources disagree": conflicted.size })}`);
